/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as ComeGuadagniamoRouteImport } from './routes/come-guadagniamo'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as EsperienzeRouteImport } from './routes/esperienze'
import { Route as LanciaRouteImport } from './routes/lancia'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as OfferteRouteImport } from './routes/offerte'
import { Route as StatoRouteImport } from './routes/stato'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as VeneziaRouteImport } from './routes/venezia'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as OfferteIndexRouteImport } from './routes/offerte.index'
import { Route as OfferteCategoryRouteImport } from './routes/offerte.$category'
import { Route as VeneziaIndexRouteImport } from './routes/venezia.index'
import { Route as Venezia48OreRouteImport } from './routes/venezia.48-ore'
import { Route as VeneziaDoveDormireRouteImport } from './routes/venezia.dove-dormire'
import { Route as OfferteCategoryIndexRouteImport } from './routes/offerte.$category.index'
import { Route as OfferteCategorySlugRouteImport } from './routes/offerte.$category.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComeGuadagniamoRoute = ComeGuadagniamoRouteImport.update({
  id: '/come-guadagniamo',
  path: '/come-guadagniamo',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const EsperienzeRoute = EsperienzeRouteImport.update({
  id: '/esperienze',
  path: '/esperienze',
  getParentRoute: () => rootRouteImport,
} as any)
const LanciaRoute = LanciaRouteImport.update({
  id: '/lancia',
  path: '/lancia',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferteRoute = OfferteRouteImport.update({
  id: '/offerte',
  path: '/offerte',
  getParentRoute: () => rootRouteImport,
} as any)
const StatoRoute = StatoRouteImport.update({
  id: '/stato',
  path: '/stato',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const VeneziaRoute = VeneziaRouteImport.update({
  id: '/venezia',
  path: '/venezia',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const OfferteIndexRoute = OfferteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfferteRoute,
} as any)
const OfferteCategoryRoute = OfferteCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => OfferteRoute,
} as any)
const VeneziaIndexRoute = VeneziaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VeneziaRoute,
} as any)
const Venezia48OreRoute = Venezia48OreRouteImport.update({
  id: '/48-ore',
  path: '/48-ore',
  getParentRoute: () => VeneziaRoute,
} as any)
const VeneziaDoveDormireRoute = VeneziaDoveDormireRouteImport.update({
  id: '/dove-dormire',
  path: '/dove-dormire',
  getParentRoute: () => VeneziaRoute,
} as any)
const OfferteCategoryIndexRoute = OfferteCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfferteCategoryRoute,
} as any)
const OfferteCategorySlugRoute = OfferteCategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OfferteCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/blog': typeof BlogRouteWithChildren
  '/chi-siamo': typeof ChiSiamoRoute
  '/come-guadagniamo': typeof ComeGuadagniamoRoute
  '/cookie': typeof CookieRoute
  '/desk': typeof DeskRoute
  '/esperienze': typeof EsperienzeRoute
  '/lancia': typeof LanciaRoute
  '/metodo': typeof MetodoRoute
  '/newsletter': typeof NewsletterRoute
  '/offerte': typeof OfferteRouteWithChildren
  '/stato': typeof StatoRoute
  '/termini': typeof TerminiRoute
  '/venezia': typeof VeneziaRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/offerte/$category': typeof OfferteCategoryRouteWithChildren
  '/venezia/48-ore': typeof Venezia48OreRoute
  '/venezia/dove-dormire': typeof VeneziaDoveDormireRoute
  '/blog/': typeof BlogIndexRoute
  '/offerte/': typeof OfferteIndexRoute
  '/venezia/': typeof VeneziaIndexRoute
  '/offerte/$category/$slug': typeof OfferteCategorySlugRoute
  '/offerte/$category/': typeof OfferteCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/chi-siamo': typeof ChiSiamoRoute
  '/come-guadagniamo': typeof ComeGuadagniamoRoute
  '/cookie': typeof CookieRoute
  '/desk': typeof DeskRoute
  '/esperienze': typeof EsperienzeRoute
  '/lancia': typeof LanciaRoute
  '/metodo': typeof MetodoRoute
  '/newsletter': typeof NewsletterRoute
  '/stato': typeof StatoRoute
  '/termini': typeof TerminiRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/venezia/48-ore': typeof Venezia48OreRoute
  '/venezia/dove-dormire': typeof VeneziaDoveDormireRoute
  '/blog': typeof BlogIndexRoute
  '/offerte': typeof OfferteIndexRoute
  '/venezia': typeof VeneziaIndexRoute
  '/offerte/$category/$slug': typeof OfferteCategorySlugRoute
  '/offerte/$category': typeof OfferteCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/blog': typeof BlogRouteWithChildren
  '/chi-siamo': typeof ChiSiamoRoute
  '/come-guadagniamo': typeof ComeGuadagniamoRoute
  '/cookie': typeof CookieRoute
  '/desk': typeof DeskRoute
  '/esperienze': typeof EsperienzeRoute
  '/lancia': typeof LanciaRoute
  '/metodo': typeof MetodoRoute
  '/newsletter': typeof NewsletterRoute
  '/offerte': typeof OfferteRouteWithChildren
  '/stato': typeof StatoRoute
  '/termini': typeof TerminiRoute
  '/venezia': typeof VeneziaRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/offerte/$category': typeof OfferteCategoryRouteWithChildren
  '/venezia/48-ore': typeof Venezia48OreRoute
  '/venezia/dove-dormire': typeof VeneziaDoveDormireRoute
  '/blog/': typeof BlogIndexRoute
  '/offerte/': typeof OfferteIndexRoute
  '/venezia/': typeof VeneziaIndexRoute
  '/offerte/$category/$slug': typeof OfferteCategorySlugRoute
  '/offerte/$category/': typeof OfferteCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/blog'
    | '/chi-siamo'
    | '/come-guadagniamo'
    | '/cookie'
    | '/desk'
    | '/esperienze'
    | '/lancia'
    | '/metodo'
    | '/newsletter'
    | '/offerte'
    | '/stato'
    | '/termini'
    | '/venezia'
    | '/blog/$slug'
    | '/offerte/$category'
    | '/venezia/48-ore'
    | '/venezia/dove-dormire'
    | '/blog/'
    | '/offerte/'
    | '/venezia/'
    | '/offerte/$category/$slug'
    | '/offerte/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/chi-siamo'
    | '/come-guadagniamo'
    | '/cookie'
    | '/desk'
    | '/esperienze'
    | '/lancia'
    | '/metodo'
    | '/newsletter'
    | '/stato'
    | '/termini'
    | '/blog/$slug'
    | '/venezia/48-ore'
    | '/venezia/dove-dormire'
    | '/blog'
    | '/offerte'
    | '/venezia'
    | '/offerte/$category/$slug'
    | '/offerte/$category'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/blog'
    | '/chi-siamo'
    | '/come-guadagniamo'
    | '/cookie'
    | '/desk'
    | '/esperienze'
    | '/lancia'
    | '/metodo'
    | '/newsletter'
    | '/offerte'
    | '/stato'
    | '/termini'
    | '/venezia'
    | '/blog/$slug'
    | '/offerte/$category'
    | '/venezia/48-ore'
    | '/venezia/dove-dormire'
    | '/blog/'
    | '/offerte/'
    | '/venezia/'
    | '/offerte/$category/$slug'
    | '/offerte/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  BlogRoute: typeof BlogRouteWithChildren
  ChiSiamoRoute: typeof ChiSiamoRoute
  ComeGuadagniamoRoute: typeof ComeGuadagniamoRoute
  CookieRoute: typeof CookieRoute
  DeskRoute: typeof DeskRoute
  EsperienzeRoute: typeof EsperienzeRoute
  LanciaRoute: typeof LanciaRoute
  MetodoRoute: typeof MetodoRoute
  NewsletterRoute: typeof NewsletterRoute
  OfferteRoute: typeof OfferteRouteWithChildren
  StatoRoute: typeof StatoRoute
  TerminiRoute: typeof TerminiRoute
  VeneziaRoute: typeof VeneziaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/come-guadagniamo': {
      id: '/come-guadagniamo'
      path: '/come-guadagniamo'
      fullPath: '/come-guadagniamo'
      preLoaderRoute: typeof ComeGuadagniamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esperienze': {
      id: '/esperienze'
      path: '/esperienze'
      fullPath: '/esperienze'
      preLoaderRoute: typeof EsperienzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancia': {
      id: '/lancia'
      path: '/lancia'
      fullPath: '/lancia'
      preLoaderRoute: typeof LanciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerte': {
      id: '/offerte'
      path: '/offerte'
      fullPath: '/offerte'
      preLoaderRoute: typeof OfferteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stato': {
      id: '/stato'
      path: '/stato'
      fullPath: '/stato'
      preLoaderRoute: typeof StatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venezia': {
      id: '/venezia'
      path: '/venezia'
      fullPath: '/venezia'
      preLoaderRoute: typeof VeneziaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/offerte/': {
      id: '/offerte/'
      path: '/'
      fullPath: '/offerte/'
      preLoaderRoute: typeof OfferteIndexRouteImport
      parentRoute: typeof OfferteRoute
    }
    '/offerte/$category': {
      id: '/offerte/$category'
      path: '/$category'
      fullPath: '/offerte/$category'
      preLoaderRoute: typeof OfferteCategoryRouteImport
      parentRoute: typeof OfferteRoute
    }
    '/venezia/': {
      id: '/venezia/'
      path: '/'
      fullPath: '/venezia/'
      preLoaderRoute: typeof VeneziaIndexRouteImport
      parentRoute: typeof VeneziaRoute
    }
    '/venezia/48-ore': {
      id: '/venezia/48-ore'
      path: '/48-ore'
      fullPath: '/venezia/48-ore'
      preLoaderRoute: typeof Venezia48OreRouteImport
      parentRoute: typeof VeneziaRoute
    }
    '/venezia/dove-dormire': {
      id: '/venezia/dove-dormire'
      path: '/dove-dormire'
      fullPath: '/venezia/dove-dormire'
      preLoaderRoute: typeof VeneziaDoveDormireRouteImport
      parentRoute: typeof VeneziaRoute
    }
    '/offerte/$category/': {
      id: '/offerte/$category/'
      path: '/'
      fullPath: '/offerte/$category/'
      preLoaderRoute: typeof OfferteCategoryIndexRouteImport
      parentRoute: typeof OfferteCategoryRoute
    }
    '/offerte/$category/$slug': {
      id: '/offerte/$category/$slug'
      path: '/$slug'
      fullPath: '/offerte/$category/$slug'
      preLoaderRoute: typeof OfferteCategorySlugRouteImport
      parentRoute: typeof OfferteCategoryRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface OfferteCategoryRouteChildren {
  OfferteCategorySlugRoute: typeof OfferteCategorySlugRoute
  OfferteCategoryIndexRoute: typeof OfferteCategoryIndexRoute
}

const OfferteCategoryRouteChildren: OfferteCategoryRouteChildren = {
  OfferteCategorySlugRoute: OfferteCategorySlugRoute,
  OfferteCategoryIndexRoute: OfferteCategoryIndexRoute,
}

const OfferteCategoryRouteWithChildren = OfferteCategoryRoute._addFileChildren(
  OfferteCategoryRouteChildren,
)

interface OfferteRouteChildren {
  OfferteCategoryRoute: typeof OfferteCategoryRouteWithChildren
  OfferteIndexRoute: typeof OfferteIndexRoute
}

const OfferteRouteChildren: OfferteRouteChildren = {
  OfferteCategoryRoute: OfferteCategoryRouteWithChildren,
  OfferteIndexRoute: OfferteIndexRoute,
}

const OfferteRouteWithChildren =
  OfferteRoute._addFileChildren(OfferteRouteChildren)

interface VeneziaRouteChildren {
  Venezia48OreRoute: typeof Venezia48OreRoute
  VeneziaDoveDormireRoute: typeof VeneziaDoveDormireRoute
  VeneziaIndexRoute: typeof VeneziaIndexRoute
}

const VeneziaRouteChildren: VeneziaRouteChildren = {
  Venezia48OreRoute: Venezia48OreRoute,
  VeneziaDoveDormireRoute: VeneziaDoveDormireRoute,
  VeneziaIndexRoute: VeneziaIndexRoute,
}

const VeneziaRouteWithChildren =
  VeneziaRoute._addFileChildren(VeneziaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  BlogRoute: BlogRouteWithChildren,
  ChiSiamoRoute: ChiSiamoRoute,
  ComeGuadagniamoRoute: ComeGuadagniamoRoute,
  CookieRoute: CookieRoute,
  DeskRoute: DeskRoute,
  EsperienzeRoute: EsperienzeRoute,
  LanciaRoute: LanciaRoute,
  MetodoRoute: MetodoRoute,
  NewsletterRoute: NewsletterRoute,
  OfferteRoute: OfferteRouteWithChildren,
  StatoRoute: StatoRoute,
  TerminiRoute: TerminiRoute,
  VeneziaRoute: VeneziaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
