import { editorialChecklist, emptyChecklist, computeConfidence } from "./checklist";
import { computeHackScore } from "./score";
import type { Offer } from "./types";

function o(
  partial: Omit<
    Offer,
    | "hackScore"
    | "currency"
    | "slug"
    | "checklist"
    | "confidence"
    | "warnings"
    | "rejectReason"
    | "sourceReliability"
    | "priceKind"
    | "publishedAt"
    | "updatedAt"
    | "datesLabel"
    | "durationLabel"
    | "included"
    | "conditions"
    | "baggage"
    | "cancellation"
    | "discovery"
    | "originHubs"
    | "flight"
    | "hotel"
  > &
    Partial<
      Pick<
        Offer,
        | "slug"
        | "checklist"
        | "warnings"
        | "rejectReason"
        | "sourceReliability"
        | "confidence"
        | "priceKind"
        | "publishedAt"
        | "updatedAt"
        | "datesLabel"
        | "durationLabel"
        | "included"
        | "conditions"
        | "baggage"
        | "cancellation"
        | "discovery"
        | "originHubs"
        | "flight"
        | "hotel"
      >
    >,
): Offer {
  const checklist = partial.checklist ?? emptyChecklist();
  const offer: Offer = {
    priceKind: "totale",
    publishedAt: null,
    updatedAt: partial.verifiedAt || null,
    datesLabel: null,
    durationLabel: null,
    included: null,
    conditions: null,
    baggage: null,
    cancellation: null,
    discovery: [],
    originHubs: ["qualsiasi"],
    flight: null,
    hotel: null,
    ...partial,
    slug: partial.slug ?? partial.id,
    currency: "EUR",
    warnings: partial.warnings ?? [],
    rejectReason: partial.rejectReason ?? "",
    sourceReliability: partial.sourceReliability ?? 7,
    checklist,
    hackScore: computeHackScore(partial.priceScore, partial.locationScore, partial.valueScore),
    confidence: 0,
  };
  offer.confidence = computeConfidence(offer);
  return offer;
}

const publishedChecks = editorialChecklist();

export const SEED_OFFERS: Offer[] = [
  o({
    id: "tokyo-02",
    slug: "milano-tokyo",
    status: "PUBBLICATO",
    category: "VOLI",
    title: "Volo diretto Milano → Tokyo",
    badge: "ERROR FARE",
    destination: "Tokyo, Giappone",
    origin: "Milano",
    price: 410,
    oldPrice: 850,
    priceKind: "andata_ritorno",
    priceScore: 10,
    locationScore: 9,
    valueScore: 10,
    verdict: "Un raro diretto sotto i 450€: da controllare bagaglio e condizioni.",
    description: "Prezzo sotto la media per un collegamento diretto. Ha senso se sei flessibile sulle date.",
    reasons: ["Prezzo sotto riferimento", "Tratta diretta", "Condizioni da verificare sul partner"],
    warnings: ["Bagaglio da confermare sul partner"],
    sourceName: "Scout voli",
    sourceUrl: "https://example.com/PLACEHOLDER",
    affiliateUrl: "https://example.com/PLACEHOLDER-replace-with-real-affiliate-link",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Skyline di Tokyo al crepuscolo",
    availability: "Verificato",
    verifiedAt: "2026-09-20T10:00:00.000Z",
    expiresAt: "2026-10-05",
    publishedAt: "2026-08-24",
    datesLabel: "12–19 novembre",
    durationLabel: "A/R · diretto",
    included: "Volo A/R diretto",
    baggage: "Solo bagaglio personale — da confermare sul partner",
    conditions: "Tariffa low-cost / error fare: variazioni e regole da leggere sul partner.",
    cancellation: "Di solito non rimborsabile. Verifica sul partner.",
    discovery: ["lungo_raggio", "error_fare"],
    originHubs: ["milano"],
    flight: {
      airline: null,
      airportFrom: "MXP",
      airportTo: "NRT",
      tripType: "AR",
      direct: true,
      duration: "circa 12h",
      stops: 0,
      baggage: "Solo bagaglio personale — da confermare",
      dates: "12–19 novembre",
      flexibleDates: false,
    },
    publishHome: true,
    featuredRank: 1,
    createdBy: "filippo",
    notes: "Hero",
    checklist: publishedChecks,
    sourceReliability: 8,
  }),
  o({
    id: "lisbon-design",
    slug: "lisbona",
    status: "PUBBLICATO",
    category: "HOTEL",
    title: "Boutique hotel design a Lisbona",
    badge: "FLASH DEAL",
    destination: "Lisbona, Portogallo",
    origin: "—",
    price: 189,
    oldPrice: 265,
    priceKind: "totale",
    priceScore: 9,
    locationScore: 10,
    valueScore: 9,
    verdict: "Buon mix tra design, posizione e prezzo per un weekend lungo.",
    description: "Struttura contemporanea, comoda da esplorare a piedi.",
    reasons: ["Posizione forte", "Sconto visibile", "Adatto a 2-3 notti"],
    sourceName: "Scout hotel",
    sourceUrl: "https://example.com/PLACEHOLDER",
    affiliateUrl: "https://example.com/PLACEHOLDER-replace-with-real-affiliate-link",
    imageUrl: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Panorama di Lisbona",
    availability: "Verificato",
    verifiedAt: "2026-08-24T10:00:00.000Z",
    expiresAt: "2026-10-06",
    publishedAt: "2026-08-24",
    datesLabel: "Weekend di settembre (date mock)",
    durationLabel: "3 notti",
    included: "Soggiorno 3 notti",
    cancellation: "Da verificare sul partner (rimborso non dato per scontato)",
    discovery: ["hotel", "weekend"],
    originHubs: ["qualsiasi"],
    hotel: {
      property: "Boutique hotel design (dataset mock)",
      area: "Centro / Chiado",
      officialRating: null,
      board: "Trattamento da confermare",
      cancellation: "Da verificare sul partner",
      nights: 3,
      pricePerNight: 63,
      dates: "Weekend di settembre (date mock)",
    },
    publishHome: true,
    featuredRank: 2,
    createdBy: "filippo",
    notes: "",
    checklist: publishedChecks,
    sourceReliability: 8,
  }),
  o({
    id: "budapest-spa",
    slug: "budapest",
    status: "PUBBLICATO",
    category: "PACCHETTI",
    title: "Weekend spa sul Danubio",
    badge: "WEEKEND HACK",
    destination: "Budapest, Ungheria",
    origin: "Venezia",
    price: 129,
    oldPrice: 189,
    priceKind: "pacchetto",
    priceScore: 10,
    locationScore: 8,
    valueScore: 9,
    verdict: "Rapporto prezzo-esperienza forte: controlla cosa è incluso.",
    description: "City break con hotel e ingresso spa.",
    reasons: ["Prezzo sotto soglia weekend", "Pacchetto più semplice del fai-da-te"],
    sourceName: "Scout pacchetti",
    sourceUrl: "https://example.com/PLACEHOLDER",
    affiliateUrl: "https://example.com/PLACEHOLDER-replace-with-real-affiliate-link",
    imageUrl: "https://images.unsplash.com/photo-1505761671935-60b3a9d0a4b1?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Budapest sul Danubio",
    availability: "Verificato",
    verifiedAt: "2026-08-27T07:00:00.000Z",
    expiresAt: "2026-10-04",
    publishedAt: "2026-08-24",
    datesLabel: "Weekend prossimo (date mock)",
    durationLabel: "2 notti",
    included: "Hotel + ingresso spa (dettaglio sul partner)",
    discovery: ["weekend"],
    originHubs: ["venezia"],
    publishHome: true,
    featuredRank: 3,
    createdBy: "filippo",
    notes: "",
    checklist: publishedChecks,
    sourceReliability: 7,
  }),
  o({
    id: "venezia-dorsoduro",
    slug: "dorsoduro",
    status: "PUBBLICATO",
    category: "VENEZIA",
    title: "Boutique hotel a Dorsoduro",
    badge: "VENEZIA PICK",
    destination: "Dorsoduro, Venezia",
    origin: "—",
    price: 178,
    oldPrice: 245,
    priceKind: "per_notte",
    priceScore: 9,
    locationScore: 10,
    valueScore: 9,
    verdict: "Se è la tua prima volta e vuoi camminare senza stress, parti da qui.",
    description: "Dorsoduro: campi più calmi e vaporetti comodi.",
    reasons: ["Posizione strategica", "Meno caos di San Marco", "Prezzo onesto per la zona"],
    sourceName: "Editoriale Venezia",
    sourceUrl: "https://example.com/PLACEHOLDER",
    affiliateUrl: "https://example.com/PLACEHOLDER-replace-with-real-affiliate-link",
    imageUrl: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Canale a Dorsoduro",
    availability: "Verificato",
    verifiedAt: "2026-08-25T09:00:00.000Z",
    expiresAt: "2026-10-12",
    publishedAt: "2026-08-25",
    datesLabel: null,
    durationLabel: "A notte",
    discovery: ["venezia", "hotel"],
    originHubs: ["venezia", "qualsiasi"],
    hotel: {
      property: "Boutique hotel Dorsoduro (dataset mock)",
      area: "Dorsoduro",
      officialRating: null,
      board: "Da confermare",
      cancellation: "Da verificare sul partner",
      nights: null,
      pricePerNight: 178,
      dates: null,
    },
    publishHome: true,
    featuredRank: 4,
    createdBy: "filippo",
    notes: "Locale pick",
    checklist: publishedChecks,
    sourceReliability: 10,
  }),
  o({
    id: "venezia-cicchetti",
    slug: "rialto-cicchetti",
    status: "PUBBLICATO",
    category: "VENEZIA",
    title: "Giro dei cicchetti a Rialto",
    badge: "VENEZIA PICK",
    destination: "Rialto, Venezia",
    origin: "—",
    price: 35,
    oldPrice: 55,
    priceKind: "esperienza",
    priceScore: 10,
    locationScore: 9,
    valueScore: 9,
    verdict: "Il modo più semplice per capire la cucina veneziana in una sera.",
    description: "Percorso tra bacari dietro Rialto.",
    reasons: ["Prezzo contenuto", "Esperienza locale"],
    sourceName: "Editoriale Venezia",
    sourceUrl: "https://example.com/PLACEHOLDER",
    affiliateUrl: "https://example.com/PLACEHOLDER-replace-with-real-affiliate-link",
    imageUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Tavolo di cicchetti",
    availability: "Verificato",
    verifiedAt: "2026-08-26T12:00:00.000Z",
    expiresAt: "2026-10-15",
    publishedAt: "2026-08-25",
    durationLabel: "Sera",
    discovery: ["venezia"],
    originHubs: ["venezia", "qualsiasi"],
    publishHome: true,
    featuredRank: 5,
    createdBy: "filippo",
    notes: "",
    checklist: publishedChecks,
    sourceReliability: 10,
  }),
  o({
    id: "venezia-mestre",
    slug: "mestre",
    status: "PUBBLICATO",
    category: "VENEZIA",
    title: "Base comoda a Mestre",
    badge: "VENEZIA PICK",
    destination: "Mestre, Venezia",
    origin: "—",
    price: 74,
    oldPrice: 110,
    priceKind: "per_notte",
    priceScore: 10,
    locationScore: 8,
    valueScore: 9,
    verdict: "Il compromesso più intelligente tra prezzo e distanza reale.",
    description: "Mestre se vuoi Venezia senza i prezzi del centro: circa 10 minuti di treno.",
    reasons: ["Prezzo basso", "Collegamento facile"],
    sourceName: "Editoriale Venezia",
    sourceUrl: "https://example.com/PLACEHOLDER",
    affiliateUrl: "https://example.com/PLACEHOLDER-replace-with-real-affiliate-link",
    imageUrl: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Treno regionale",
    availability: "Verificato",
    verifiedAt: "2026-08-25T09:00:00.000Z",
    expiresAt: "2026-10-12",
    publishedAt: "2026-08-25",
    durationLabel: "A notte",
    discovery: ["venezia", "hotel"],
    originHubs: ["venezia", "qualsiasi"],
    hotel: {
      property: "Hotel vicino Mestre FS (dataset mock)",
      area: "Mestre",
      officialRating: null,
      board: "Da confermare",
      cancellation: "Da verificare sul partner",
      nights: null,
      pricePerNight: 74,
      dates: null,
    },
    publishHome: true,
    featuredRank: 6,
    createdBy: "filippo",
    notes: "",
    checklist: publishedChecks,
    sourceReliability: 10,
  }),
  o({
    id: "barcelona-weekend",
    slug: "venezia-barcellona",
    status: "REVIEW",
    category: "VOLI",
    title: "Venezia → Barcellona",
    badge: "CITY BREAK",
    destination: "Barcellona, Spagna",
    origin: "Venezia",
    price: 59,
    oldPrice: 119,
    priceKind: "andata_ritorno",
    priceScore: 10,
    locationScore: 8,
    valueScore: 8,
    verdict: "Classico low-cost: ottimo se il bagaglio resta basso.",
    description: "Weekend urbano con solo zaino.",
    reasons: ["Sconto forte", "Tratta breve", "Bagaglio da verificare"],
    sourceName: "Scout voli",
    sourceUrl: "https://example.com/PLACEHOLDER",
    affiliateUrl: "https://example.com/PLACEHOLDER-replace-with-real-affiliate-link",
    imageUrl: "https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Barcellona",
    availability: "Da verificare",
    verifiedAt: "",
    expiresAt: null,
    datesLabel: "Weekend (date da confermare)",
    durationLabel: "A/R",
    baggage: "Spesso solo personale — da verificare",
    discovery: ["weekend"],
    originHubs: ["venezia"],
    flight: {
      airline: null,
      airportFrom: "VCE",
      airportTo: "BCN",
      tripType: "AR",
      direct: true,
      duration: "circa 2h",
      stops: 0,
      baggage: "Da verificare",
      dates: null,
      flexibleDates: true,
    },
    publishHome: false,
    featuredRank: 0,
    createdBy: "bot-voli-01",
    notes: "In coda revisione",
    sourceReliability: 6,
  }),
  o({
    id: "marrakech-riad",
    slug: "marrakech",
    status: "CANDIDATO",
    category: "HOTEL",
    title: "Riad con piscina a Marrakech",
    badge: "HIDDEN GEM",
    destination: "Marrakech, Marocco",
    origin: "—",
    price: 96,
    oldPrice: 150,
    priceKind: "per_notte",
    priceScore: 10,
    locationScore: 9,
    valueScore: 9,
    verdict: "Esperienza alta rispetto alla spesa.",
    description: "Piscina dopo la medina.",
    reasons: ["Prezzo competitivo", "Location da confermare"],
    sourceName: "Scout hotel",
    sourceUrl: "https://example.com/PLACEHOLDER",
    affiliateUrl: "https://example.com/PLACEHOLDER-replace-with-real-affiliate-link",
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Architettura marocchina",
    availability: "Da verificare",
    verifiedAt: "",
    expiresAt: null,
    discovery: ["hotel", "mare"],
    originHubs: ["qualsiasi"],
    hotel: {
      property: "Riad (dataset mock)",
      area: "Medina — da confermare",
      officialRating: null,
      board: "Da confermare",
      cancellation: "Da verificare",
      nights: null,
      pricePerNight: 96,
      dates: null,
    },
    publishHome: false,
    featuredRank: 0,
    createdBy: "bot-hotel-01",
    notes: "",
    sourceReliability: 6,
  }),
  o({
    id: "atene-scaduto",
    slug: "roma-atene",
    status: "SCADUTO",
    category: "VOLI",
    title: "Roma → Atene (scaduta)",
    badge: "CITY BREAK",
    destination: "Atene, Grecia",
    origin: "Roma",
    price: 39,
    oldPrice: 98,
    priceKind: "andata_ritorno",
    priceScore: 10,
    locationScore: 8,
    valueScore: 7,
    verdict: "Era un low-cost pulito. Non è più in pubblicazione.",
    description: "Esempio di stato SCADUTO: un travel deal non è evergreen.",
    reasons: ["Prezzo sotto soglia al momento del controllo"],
    warnings: ["Offerta scaduta — non prenotare da questa scheda"],
    sourceName: "Scout voli",
    sourceUrl: "https://example.com/PLACEHOLDER",
    affiliateUrl: "https://example.com/PLACEHOLDER-replace-with-real-affiliate-link",
    imageUrl: "https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Atene",
    availability: "Scaduta",
    verifiedAt: "2026-08-18T08:00:00.000Z",
    expiresAt: "2026-08-20",
    publishedAt: "2026-08-18",
    datesLabel: "Date non più valide",
    durationLabel: "A/R",
    discovery: ["weekend"],
    originHubs: ["roma"],
    publishHome: false,
    featuredRank: 0,
    createdBy: "filippo",
    notes: "Stato UI: scaduta",
    checklist: publishedChecks,
    sourceReliability: 7,
  }),
];
